(define (problem blocks-005-2)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b2) (clear b4) (handempty) (on b0 b1) (on b2 b3) (on b4 b0) (ontable b1) (ontable b3))
    (:goal (clear b0))
)