(define (problem blocks-004-2)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b0) (clear b1) (handempty) (on b1 b2) (on b2 b3) (ontable b0) (ontable b3))
    (:goal (clear b3))
)