(define (problem problem-half-4-1)
    (:domain grid-visit-all)
    (:objects loc_x0_y0 loc_x0_y2 loc_x1_y3 loc_x2_y1 loc_x2_y2 loc_x3_y0 - place)
    (:init (at-robot loc_x2_y2) (connected loc_x2_y1 loc_x2_y2) (connected loc_x2_y2 loc_x2_y1) (visited loc_x2_y2))
    (:goal (and (visited loc_x0_y0) (visited loc_x0_y2) (visited loc_x1_y3) (visited loc_x2_y1) (visited loc_x2_y2) (visited loc_x3_y0)))
)