(define (problem problem-6-1)
    (:domain blocksworld-3ops)
    (:objects b1 b2 b3 b4 b5 b6)
    (:init (arm-empty) (clear b2) (clear b5) (clear b6) (on b2 b3) (on b5 b1) (on b6 b4) (on-table b1) (on-table b3) (on-table b4))
    (:goal (and (on b3 b6) (on b4 b3)))
)