(define (problem problem-4-3)
    (:domain blocksworld-3ops)
    (:objects b1 b2 b3 b4)
    (:init (arm-empty) (clear b4) (on b1 b3) (on b3 b2) (on b4 b1) (on-table b2))
    (:goal (and (on b1 b3) (on b2 b4) (on b4 b1)))
)