(define (problem problem-4-4)
    (:domain blocksworld-3ops)
    (:objects b1 b2 b3 b4)
    (:init (arm-empty) (clear b3) (on b1 b2) (on b2 b4) (on b3 b1) (on-table b4))
    (:goal (and (on b1 b4) (on b3 b1)))
)