(define (problem problem-5-5)
    (:domain blocksworld-3ops)
    (:objects b1 b2 b3 b4 b5)
    (:init (arm-empty) (clear b1) (clear b2) (on b1 b3) (on b2 b4) (on b3 b5) (on-table b4) (on-table b5))
    (:goal (and (on b2 b4) (on b4 b3) (on b5 b2)))
)