(define (problem problem-4-5)
    (:domain blocksworld-3ops)
    (:objects b1 b2 b3 b4)
    (:init (arm-empty) (clear b2) (clear b4) (on b2 b1) (on b4 b3) (on-table b1) (on-table b3))
    (:goal (and (on b2 b3) (on b3 b4)))
)