(define (problem problem-4-2)
    (:domain blocksworld-3ops)
    (:objects b1 b2 b3 b4)
    (:init (arm-empty) (clear b3) (clear b4) (on b2 b1) (on b3 b2) (on-table b1) (on-table b4))
    (:goal (and (on b1 b3) (on b2 b4) (on b4 b1)))
)