(define (problem blocks-003-5)
    (:domain blocks3ops)
    (:requirements :equality :non-deterministic :strips)
    (:objects b0 b1 b2)
    (:init (clear b1) (clear b2) (on b2 b0) (ontable b0) (ontable b1))
    (:goal (and (clear b0) (on b0 b2) (ontable b2)))
)