(define (problem blocks-006-4)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5)
    (:init (clear b2) (clear b5) (handempty) (on b0 b4) (on b2 b3) (on b3 b1) (on b5 b0) (ontable b1) (ontable b4))
    (:goal (clear b1))
)