(define (problem blocks-008-1)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6 b7)
    (:init (clear b0) (clear b3) (clear b4) (handempty) (on b0 b7) (on b1 b2) (on b3 b6) (on b4 b5) (on b7 b1) (ontable b2) (ontable b5) (ontable b6))
    (:goal (clear b5))
)