(define (problem gripper-6-4)
    (:domain gripper-strips)
    (:objects ball1 ball2 ball3 ball4 ball5 ball6 left right rooma roomb)
    (:init (at ball1 rooma) (at ball2 rooma) (at ball3 rooma) (at ball4 rooma) (at ball5 rooma) (at ball6 rooma) (at-robby rooma) (ball ball1) (ball ball2) (ball ball3) (ball ball4) (ball ball5) (ball ball6) (free left) (free right) (gripper left) (gripper right) (room rooma) (room roomb))
    (:goal (and (at ball1 roomb) (at ball2 roomb) (at ball3 roomb) (at ball4 roomb) (at ball5 roomb) (at ball6 roomb)))
)