policy_type: DATALOG
policy_iterations: 1
abort_on_cycle: true
solve_prog: solve_datalog_action_params.lp
include_action_params: true
include_roles: false
include_concepts: false
include_dead_states: false
include_goal_states: false