(define (problem blocks-8-0)
(:domain blocks)
(:objects h g f e c b d a )
(:init (clear a) (clear d) (clear b) (clear c) (ontable e) (ontable f)
 (ontable b) (ontable c) (on a g) (on g e) (on d h) (on h f) (handempty))
(:goal (and (clear a)))
)