(define (problem blocks-5-clear)
(:domain blocks)
(:objects a b c d e)
(:init
    (ontable a)
    (ontable b)
    (ontable c)
    (ontable d)
    (ontable e)
    (clear a)
    (clear b)
    (clear c)
    (clear d)
    (clear e)
    (handempty))
(:goal (and (clear a))))
