(define (problem blocks-002-3)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1)
    (:init (clear b0) (clear b1) (handempty) (ontable b0) (ontable b1))
    (:goal (on b1 b0))
)