(define (problem blocks-003-5)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2)
    (:init (clear b0) (clear b1) (handempty) (on b0 b2) (ontable b1) (ontable b2))
    (:goal (on b2 b0))
)