(define (problem blocks-004-3)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b1) (clear b2) (clear b3) (handempty) (on b1 b0) (ontable b0) (ontable b2) (ontable b3))
    (:goal (on b1 b2))
)