(define (problem blocks-004-4)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b2) (handempty) (on b1 b3) (on b2 b1) (on b3 b0) (ontable b0))
    (:goal (on b0 b1))
)