(define (problem blocks-004-1)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b2) (clear b3) (handempty) (on b0 b1) (on b3 b0) (ontable b1) (ontable b2))
    (:goal (on b2 b0))
)