(define (problem blocks-005-4)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b0) (handempty) (on b0 b2) (on b2 b4) (on b3 b1) (on b4 b3) (ontable b1))
    (:goal (on b2 b4))
)