(define (problem blocks-005-5)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b1) (clear b3) (handempty) (on b0 b2) (on b1 b0) (on b2 b4) (ontable b3) (ontable b4))
    (:goal (on b3 b1))
)