(define (problem blocks-005-08)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b1) (clear b3) (handempty) (on b2 b4) (on b3 b2) (on b4 b0) (ontable b0) (ontable b1))
    (:goal (on b4 b2))
)