(define (problem blocks-005-1)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b0) (clear b2) (clear b4) (handempty) (on b0 b1) (on b1 b3) (ontable b2) (ontable b3) (ontable b4))
    (:goal (on b0 b1))
)