(define (problem blocks-006-5)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5)
    (:init (clear b0) (clear b5) (handempty) (on b1 b2) (on b2 b3) (on b4 b1) (on b5 b4) (ontable b0) (ontable b3))
    (:goal (on b5 b0))
)