(define (problem blocks-006-3)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5)
    (:init (clear b0) (clear b4) (handempty) (on b1 b3) (on b2 b5) (on b4 b2) (on b5 b1) (ontable b0) (ontable b3))
    (:goal (on b3 b0))
)