(define (problem blocks-007-4)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6)
    (:init (clear b1) (clear b3) (clear b5) (clear b6) (handempty) (on b0 b2) (on b1 b4) (on b4 b0) (ontable b2) (ontable b3) (ontable b5) (ontable b6))
    (:goal (on b2 b0))
)