(define (problem blocks-007-5)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6)
    (:init (clear b0) (clear b1) (clear b2) (clear b3) (clear b4) (clear b6) (handempty) (on b0 b5) (ontable b1) (ontable b2) (ontable b3) (ontable b4) (ontable b5) (ontable b6))
    (:goal (on b0 b3))
)