(define (problem blocks-007-10)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6)
    (:init (clear b0) (clear b2) (clear b6) (handempty) (on b3 b5) (on b4 b3) (on b5 b1) (on b6 b4) (ontable b0) (ontable b1) (ontable b2))
    (:goal (on b3 b2))
)