(define (problem blocks-008-2)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6 b7)
    (:init (clear b0) (clear b2) (clear b4) (handempty) (on b1 b5) (on b3 b1) (on b4 b6) (on b6 b7) (on b7 b3) (ontable b0) (ontable b2) (ontable b5))
    (:goal (on b7 b5))
)