(define (problem blocks-009-4)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6 b7 b8)
    (:init (clear b0) (clear b4) (clear b5) (clear b7) (handempty) (on b0 b8) (on b2 b3) (on b3 b1) (on b4 b2) (on b8 b6) (ontable b1) (ontable b5) (ontable b6) (ontable b7))
    (:goal (on b7 b6))
)