(define (problem tireworld-006-02)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 - location)
    (:init (road l0 l1) (road l1 l0) (road l1 l5) (road l2 l0) (road l3 l4) (road l3 l5) (road l4 l2) (road l4 l3) (spare-in l3) (vehicle-at l4))
    (:goal (vehicle-at l5))
)