(define (problem tireworld-006-09)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 - location)
    (:init (road l0 l5) (road l1 l0) (road l2 l1) (road l2 l5) (road l3 l0) (road l4 l2) (road l5 l3) (spare-in l0) (spare-in l1) (spare-in l2) (spare-in l5) (vehicle-at l4))
    (:goal (vehicle-at l3))
)