(define (problem tireworld-009-04)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 l7 l8 - location)
    (:init (road l0 l4) (road l0 l5) (road l1 l5) (road l1 l6) (road l2 l0) (road l2 l3) (road l3 l7) (road l4 l0) (road l4 l6) (road l5 l1) (road l6 l4) (road l7 l6) (road l8 l2) (spare-in l0) (spare-in l2) (spare-in l3) (spare-in l4) (spare-in l6) (spare-in l7) (vehicle-at l8))
    (:goal (vehicle-at l5))
)