(define (problem tireworld-009-01)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 l7 l8 - location)
    (:init (road l0 l2) (road l0 l4) (road l0 l6) (road l1 l7) (road l2 l3) (road l3 l4) (road l4 l5) (road l6 l0) (road l7 l6) (road l8 l1) (road l8 l7) (spare-in l0) (spare-in l4) (spare-in l6) (spare-in l7) (vehicle-at l8))
    (:goal (vehicle-at l5))
)