(define (problem tireworld-009-03)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 l7 l8 - location)
    (:init (road l0 l7) (road l1 l4) (road l2 l4) (road l2 l7) (road l3 l0) (road l3 l1) (road l4 l2) (road l4 l8) (road l5 l7) (road l6 l8) (road l7 l0) (road l7 l5) (road l7 l6) (road l8 l4) (spare-in l0) (spare-in l1) (spare-in l2) (spare-in l4) (spare-in l6) (spare-in l7) (spare-in l8) (vehicle-at l3))
    (:goal (vehicle-at l5))
)