(define (problem tireworld-010-01)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 l7 l8 l9 - location)
    (:init (road l0 l4) (road l1 l9) (road l3 l1) (road l4 l6) (road l5 l8) (road l6 l3) (road l6 l4) (road l7 l2) (road l8 l0) (road l9 l7) (spare-in l0) (spare-in l1) (spare-in l3) (spare-in l4) (spare-in l6) (spare-in l7) (spare-in l8) (spare-in l9) (vehicle-at l5))
    (:goal (vehicle-at l2))
)