(define (problem tireworld-010-10)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 l7 l8 l9 - location)
    (:init (road l0 l8) (road l1 l6) (road l2 l6) (road l3 l4) (road l3 l5) (road l4 l7) (road l5 l3) (road l5 l9) (road l6 l0) (road l6 l1) (road l7 l1) (road l8 l9) (road l9 l5) (spare-in l0) (spare-in l6) (spare-in l8) (vehicle-at l2))
    (:goal (vehicle-at l9))
)