(define (problem tireworld-010-08)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 l7 l8 l9 - location)
    (:init (road l0 l3) (road l0 l6) (road l1 l4) (road l1 l5) (road l2 l6) (road l2 l8) (road l3 l2) (road l4 l6) (road l5 l9) (road l7 l3) (road l8 l1) (road l9 l7) (spare-in l1) (spare-in l2) (spare-in l4) (spare-in l5) (spare-in l7) (spare-in l8) (vehicle-at l0))
    (:goal (vehicle-at l6))
)