(define (problem problem-4-3)
    (:domain blocksworld-4ops)
    (:objects b1 b2 b3 b4)
    (:init (arm-empty) (clear b2) (clear b3) (on b2 b1) (on b3 b4) (on-table b1) (on-table b4))
    (:goal (and (on b2 b4) (on b4 b3)))
)