(define (problem problem-7-5)
    (:domain blocksworld-4ops)
    (:objects b1 b2 b3 b4 b5 b6 b7)
    (:init (arm-empty) (clear b1) (clear b3) (clear b4) (clear b5) (clear b7) (on b1 b2) (on b7 b6) (on-table b2) (on-table b3) (on-table b4) (on-table b5) (on-table b6))
    (:goal (and (on b1 b7) (on b2 b6) (on b3 b2) (on b4 b5) (on b5 b3)))
)