(define (problem problem-5-4)
    (:domain blocksworld-4ops)
    (:objects b1 b2 b3 b4 b5)
    (:init (arm-empty) (clear b1) (clear b2) (on b1 b3) (on b3 b4) (on b4 b5) (on-table b2) (on-table b5))
    (:goal (and (on b2 b4) (on b5 b3)))
)