(define (problem problem-4-5)
    (:domain blocksworld-4ops)
    (:objects b1 b2 b3 b4)
    (:init (arm-empty) (clear b1) (clear b2) (on b2 b3) (on b3 b4) (on-table b1) (on-table b4))
    (:goal (and (on b2 b3) (on b3 b4)))
)