(define (problem problem-6-1)
    (:domain blocksworld-4ops)
    (:objects b1 b2 b3 b4 b5 b6)
    (:init (arm-empty) (clear b2) (clear b3) (clear b5) (on b2 b6) (on b3 b4) (on b6 b1) (on-table b1) (on-table b4) (on-table b5))
    (:goal (and (on b2 b3) (on b3 b6) (on b6 b1)))
)