(define (problem blocks-004-2)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b2) (handempty) (on b0 b1) (on b2 b3) (on b3 b0) (ontable b1))
    (:goal (and (clear b3) (on b3 b2) (on b2 b1) (on b1 b0) (ontable b0)))
)