(define (problem blocks-004-5)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b0) (clear b1) (clear b3) (handempty) (on b0 b2) (ontable b1) (ontable b2) (ontable b3))
    (:goal (and (clear b0) (on b0 b1) (on b1 b3) (on b3 b2) (ontable b2)))
)