(define (problem blocks-005-1)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b0) (clear b1) (clear b2) (clear b3) (clear b4) (handempty) (ontable b0) (ontable b1) (ontable b2) (ontable b3) (ontable b4))
    (:goal (and (clear b4) (on b4 b3) (ontable b3)))
)