(define (problem blocks-006-4)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5)
    (:init (clear b2) (clear b4) (clear b5) (handempty) (on b0 b1) (on b1 b3) (on b5 b0) (ontable b2) (ontable b3) (ontable b4))
    (:goal (and (on b3 b4) (on b4 b0) (on b0 b5) (on b5 b1) (on b1 b2)))
)