(define (problem pb6)
   (:domain blocksworld)
   (:objects a b c d e f)
   (:init (ontable a) (ontable b) (ontable c) (ontable d) (ontable e) 
          (ontable f)
          (clear a)  (clear b) (clear c) (clear d) (clear e) 
          (clear f) 
          (handempty))
   (:goal (and (on a b) (on b c) (on c d) (on d e) (on e f))))