(define (problem tower9)
   (:domain blocksworld)
   (:objects a b c d e f g h i)
   (:init (ontable a) (ontable b) (ontable c) (ontable d) (ontable e) 
          (ontable f) (ontable g) (ontable h) (ontable i) 
          (clear a)  (clear b) (clear c) (clear d) (clear e) 
          (clear f)  (clear g) (clear h) (clear i) (handempty))
   (:goal (and (on a b) (on b c) (on c d) (on d e) (on e f) (on f g)
               (on g h) (on h i))))