(define (problem acrobatics-3-down)
    (:domain acrobatics)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects p0 p1 p2 - location)
    (:init (ladder-at p0) (next-bwd p1 p0) (next-bwd p2 p1) (next-fwd p0 p1) (next-fwd p1 p2) (position p0))
    (:goal (and (up) (position p2)))
)