(define (problem blocks-004-1)
    (:domain blocks3ops)
    (:objects b0 b1 b2 b3)
    (:init (clear b1) (clear b3) (on b0 b2) (on b3 b0) (ontable b1) (ontable b2))
    (:goal (and (clear b0) (on b0 b2) (ontable b2)))
)