(define (problem blocks-005-4)
    (:domain blocks3ops)
    (:requirements :equality :non-deterministic :strips)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b3) (clear b4) (on b1 b2) (on b2 b0) (on b4 b1) (ontable b0) (ontable b3))
    (:goal (and (clear b2) (on b2 b4) (on b4 b0) (ontable b0)))
)