(define (problem pb3)
   (:domain blocks2)
   (:objects a b c)
   (:init (ontable a) (ontable b)   (ontable c)  
          (clear a)  (clear b) (clear c)
          (neq a b) (neq a c)
          (neq b a) (neq b c)
          (neq c a) (neq c b))
   (:goal (and (on a b) (on b c))))

