(define (problem pb4)
   (:domain blocks2)
   (:objects a b c d)
   (:init (ontable a) (on b a) (on c b) (on d c) (clear d)
          (neq a b) (neq a c) (neq a d)
          (neq b a) (neq b c) (neq b d)
          (neq c a) (neq c b) (neq c d)
          (neq d a) (neq d b) (neq d c))
   (:goal (and (on b a) (on c b) (on a d))))
