(define (problem blocks-006-04)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5)
    (:init (clear b1) (clear b2) (clear b5) (handempty) (on b0 b4) (on b4 b3) (on b5 b0) (ontable b1) (ontable b2) (ontable b3))
    (:goal (on b0 b5))
)