(define (problem tireworld-004-2)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 - location)
    (:init (road l0 l1) (road l0 l3) (road l1 l0) (road l1 l2) (road l2 l1) (road l3 l0) (spare-in l0) (spare-in l1) (vehicle-at l3))
    (:goal (vehicle-at l2))
)