(define (problem tireworld-004-3)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 - location)
    (:init (road l1 l2) (road l2 l1) (road l2 l3) (road l3 l2) (vehicle-at l2))
    (:goal (vehicle-at l3))
)