(define (problem tireworld-005-6)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 - location)
    (:init (road l0 l1) (road l1 l0) (road l1 l2) (road l1 l4) (road l2 l1) (road l2 l3) (road l3 l2) (road l3 l4) (road l4 l1) (road l4 l3) (spare-in l1) (vehicle-at l4))
    (:goal (vehicle-at l0))
)