(define (problem tireworld-007-08)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 - location)
    (:init (road l0 l4) (road l0 l5) (road l1 l5) (road l1 l6) (road l2 l4) (road l2 l6) (road l3 l6) (road l4 l0) (road l4 l2) (road l5 l0) (road l5 l1) (road l5 l6) (road l6 l1) (road l6 l2) (road l6 l3) (road l6 l5) (spare-in l0) (spare-in l5) (spare-in l6) (vehicle-at l3))
    (:goal (vehicle-at l4))
)