(define (problem tireworld-007-06)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 - location)
    (:init (road l0 l3) (road l1 l3) (road l1 l4) (road l1 l5) (road l2 l3) (road l2 l4) (road l3 l0) (road l3 l1) (road l3 l2) (road l3 l6) (road l4 l1) (road l4 l2) (road l5 l1) (road l5 l6) (road l6 l3) (road l6 l5) (spare-in l2) (spare-in l3) (spare-in l5) (spare-in l6) (vehicle-at l0))
    (:goal (vehicle-at l1))
)