(define (problem tireworld-009-01)
    (:domain tire-adl)
    (:requirements :negative-preconditions :non-deterministic :strips :typing)
    (:objects l0 l1 l2 l3 l4 l5 l6 l7 l8 - location)
    (:init (road l0 l1) (road l1 l0) (road l2 l3) (road l3 l2) (road l3 l4) (road l4 l3) (road l5 l6) (road l5 l7) (road l6 l5) (road l6 l7) (road l7 l5) (road l7 l6) (vehicle-at l7))
    (:goal (vehicle-at l5))
)