(define (problem blocks-004-05)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b0) (clear b1) (handempty) (on b0 b2) (on b1 b3) (ontable b2) (ontable b3))
    (:goal (on b1 b0))
)