(define (problem blocks-004-01)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b0) (clear b1) (clear b3) (handempty) (on b1 b2) (ontable b0) (ontable b2) (ontable b3))
    (:goal (on b0 b2))
)