(define (problem blocks-007-02)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6)
    (:init (clear b2) (clear b3) (clear b6) (handempty) (on b0 b5) (on b1 b4) (on b5 b1) (on b6 b0) (ontable b2) (ontable b3) (ontable b4))
    (:goal (on b2 b1))
)