(define (problem blocks-007-04)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6)
    (:init (clear b3) (clear b6) (handempty) (on b0 b2) (on b2 b1) (on b4 b5) (on b5 b0) (on b6 b4) (ontable b1) (ontable b3))
    (:goal (on b4 b6))
)