(define (problem blocks-004-3)
    (:domain blocks3ops)
    (:requirements :equality :non-deterministic :strips)
    (:objects b0 b1 b2 b3)
    (:init (clear b2) (on b0 b1) (on b1 b3) (on b2 b0) (ontable b3))
    (:goal (and (clear b2) (on b2 b0) (on b0 b3) (ontable b3)))
)