(define (problem BLOCKS-16-1)
(:domain BLOCKS)
(:objects K C D B I N P J M L G E A O H F )
(:init (clear F) (clear H) (clear O) (ontable A) (ontable E) (ontable G)
 (on F L) (on L M) (on M J) (on J P) (on P N) (on N I) (on I B) (on B D)
 (on D C) (on C K) (on K A) (on H E) (on O G) (handempty))
(:goal (and (on D B) (on B P) (on P F) (on F G) (on G K) (on K I) (on I L)
            (on L J) (on J H) (on H A) (on A N) (on N E) (on E M) (on M C)
            (on C O)))
)