(define (problem BLOCKS-11-0)
(:domain BLOCKS)
(:objects F A K H G E D I C J B )
(:init (clear B) (clear J) (clear C) (ontable I) (ontable D) (ontable E)
 (on B G) (on G H) (on H K) (on K A) (on A F) (on F I) (on J D) (on C E)
 (handempty))
(:goal (and (on A J) (on J D) (on D B) (on B H) (on H K) (on K I) (on I F)
            (on F E) (on E G) (on G C)))
)