(define (problem BLOCKS-13-1)
(:domain BLOCKS)
(:objects I M G H L A C D E K F B J )
(:init (clear J) (clear B) (ontable F) (ontable K) (on J E) (on E D) (on D C)
 (on C A) (on A L) (on L H) (on H G) (on G M) (on M I) (on I F) (on B K)
 (handempty))
(:goal (and (on D A) (on A E) (on E L) (on L M) (on M C) (on C J) (on J F)
            (on F K) (on K G) (on G H) (on H I) (on I B)))
)