(define (problem BLOCKS-13-0)
(:domain BLOCKS)
(:objects L H E A J C D F G K M I B )
(:init (clear B) (clear I) (clear M) (ontable K) (ontable G) (ontable M)
 (on B F) (on F D) (on D C) (on C J) (on J A) (on A E) (on E H) (on H L)
 (on L K) (on I G) (handempty))
(:goal (and (on G I) (on I C) (on C D) (on D F) (on F A) (on A M) (on M H)
            (on H E) (on E L) (on L J) (on J B) (on B K)))
)