(define (problem BLOCKS-15-1)
(:domain BLOCKS)
(:objects J B K A D H E N C F L M I O G )
(:init (clear G) (clear O) (ontable I) (ontable M) (on G L) (on L F) (on F C)
 (on C N) (on N E) (on E H) (on H D) (on D A) (on A K) (on K B) (on B J)
 (on J I) (on O M) (handempty))
(:goal (and (on D G) (on G F) (on F K) (on K J) (on J E) (on E M) (on M A)
            (on A B) (on B C) (on C N) (on N O) (on O I) (on I L) (on L H)))
)