(define (problem BLOCKS-16-2)
(:domain BLOCKS)
(:objects K I G N P A D M C B H F O J L E )
(:init (clear E) (clear L) (ontable J) (ontable O) (on E F) (on F H) (on H B)
 (on B C) (on C M) (on M D) (on D A) (on A P) (on P N) (on N G) (on G I)
 (on I K) (on K J) (on L O) (handempty))
(:goal (and (on I D) (on D H) (on H F) (on F B) (on B K) (on K J) (on J G)
            (on G E) (on E C) (on C L) (on L M) (on M N) (on N A) (on A P)
            (on P O)))
)