(define (problem BLOCKS-15-0)
(:domain BLOCKS)
(:objects A C L D J H K O N G I F B M E )
(:init (clear E) (clear M) (clear B) (clear F) (clear I) (ontable G)
 (ontable N) (ontable O) (ontable K) (ontable H) (on E J) (on J D) (on D L)
 (on L C) (on C G) (on M N) (on B A) (on A O) (on F K) (on I H) (handempty))
(:goal (and (on G O) (on O H) (on H K) (on K M) (on M F) (on F E) (on E A)
            (on A B) (on B L) (on L J) (on J D) (on D N) (on N I) (on I C)))
)