(define (problem BLOCKS-11-1)
(:domain BLOCKS)
(:objects B C E A H K I G D F J )
(:init (clear J) (clear F) (clear D) (clear G) (ontable I) (ontable K)
 (ontable H) (ontable A) (on J I) (on F E) (on E K) (on D C) (on C H) (on G B)
 (on B A) (handempty))
(:goal (and (on B D) (on D J) (on J K) (on K H) (on H A) (on A C) (on C F)
            (on F G) (on G I) (on I E)))
)