(define (problem BLOCKS-14-1)
(:domain BLOCKS)
(:objects K A F L D B M E J N H I C G )
(:init (clear G) (clear C) (clear I) (clear H) (clear N) (ontable J)
 (ontable E) (ontable M) (ontable B) (ontable N) (on G J) (on C E) (on I D)
 (on D L) (on L M) (on H F) (on F A) (on A K) (on K B) (handempty))
(:goal (and (on J D) (on D B) (on B H) (on H M) (on M K) (on K F) (on F G)
            (on G A) (on A I) (on I E) (on E L) (on L N) (on N C)))
)