(define (problem blocks-004-10)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b1) (clear b3) (handempty) (on b0 b2) (on b1 b0) (ontable b2) (ontable b3))
    (:goal (on b3 b0))
)