(define (problem blocks-006-01)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5)
    (:init (clear b0) (clear b2) (clear b4) (clear b5) (handempty) (on b0 b3) (on b3 b1) (ontable b1) (ontable b2) (ontable b4) (ontable b5))
    (:goal (on b2 b5))
)