(define (problem blocks-007-09)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6)
    (:init (clear b0) (clear b2) (clear b3) (clear b4) (handempty) (on b0 b6) (on b2 b5) (on b4 b1) (ontable b1) (ontable b3) (ontable b5) (ontable b6))
    (:goal (on b6 b3))
)