(define (problem blocks-004-4)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3)
    (:init (clear b1) (clear b3) (handempty) (on b0 b2) (on b3 b0) (ontable b1) (ontable b2))
    (:goal (clear b0))
)