(define (problem blocks-005-5)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4)
    (:init (clear b1) (clear b3) (clear b4) (handempty) (on b1 b2) (on b4 b0) (ontable b0) (ontable b2) (ontable b3))
    (:goal (clear b0))
)