(define (problem blocks-008-5)
    (:domain blocksworld)
    (:requirements :strips :typing)
    (:objects b0 b1 b2 b3 b4 b5 b6 b7)
    (:init (clear b4) (clear b6) (handempty) (on b0 b5) (on b2 b7) (on b3 b0) (on b4 b1) (on b5 b2) (on b6 b3) (ontable b1) (ontable b7))
    (:goal (clear b0))
)